Vagrant.configure("2") do |config|
  machines = {
    "ubuntu" => "ubuntu/jammy64",
    "debian" => "debian/bookworm64",
    "fedora" => "generic/fedora40",
    "rocky" => "generic/rocky9",
  }

  machines.each do |name, box|
    config.vm.define name do |machine|
      machine.vm.box = box
      machine.vm.hostname = "wansim-#{name}"
      machine.vm.network "private_network", type: "dhcp"
      machine.vm.provision "shell", path: "provision.sh", privileged: true
    end
  end
end
