Vagrant.configure("2") do |config|
  provider = ENV.fetch("VAGRANT_PROVIDER", "virtualbox")
  repository = File.expand_path("../..", __dir__)
  machines = {
    "ubuntu" => { box: "ubuntu/noble64", image: "ubuntu:24.04" },
    "debian" => { box: "debian/bookworm64", image: "debian:12" },
    "fedora" => { box: "generic/fedora42", image: "fedora:42" },
    "rocky" => { box: "generic/rocky9", image: "rockylinux:9" },
  }

  config.vm.synced_folder ".", "/vagrant", disabled: true

  machines.each do |name, platform|
    config.vm.define name do |machine|
      machine.vm.hostname = "wansim-#{name}"
      machine.vm.synced_folder repository, "/vagrant"

      if provider == "docker"
        machine.vm.provider "docker" do |docker|
          docker.build_dir = File.expand_path("vagrant-docker", __dir__)
          docker.build_args = ["--build-arg", "BASE_IMAGE=#{platform[:image]}"]
          docker.name = "wansim-vagrant-#{name}-#{ENV.fetch('GITHUB_RUN_ID', 'local')}"
          docker.has_ssh = false
          docker.remains_running = true
          docker.create_args = [
            "--privileged", "--cgroupns=host", "--tmpfs=/run", "--tmpfs=/run/lock",
          ]
          docker.volumes = ["/sys/fs/cgroup:/sys/fs/cgroup:rw"]
          docker.cmd = ["/sbin/init"]
        end
      else
        machine.vm.box = platform[:box]
        machine.vm.network "private_network", type: "dhcp"
        machine.vm.provision "shell", inline: "bash /vagrant/v2/integration/installer-lifecycle.sh", privileged: true
      end
    end
  end
end
